# Generated by Django 2.0.1 on 2018-01-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('invitorID', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
